### ISSUE TITLE
Network>Staking>Payout displays old Eras that have already been paid

### ISSUE THREAD

**Issue by the-nodelab** [polkadot-js/apps#10513]
I'm submitting a Bug report

The Network>Staking>Payout displays old Eras that have already been paid and so causes an error stating 'Already claimed' when you claim again.

It is not possible to know which eras have been paid.

On older versions, the only Eras displayed were those that had not yet been paid out.

The Payout page needs updating to only display Eras that have not yet been paid.

Running on A Windows 11 PC using Brave Browser (shields off for this webpage) - also tried on Chrome, Edge and FileFox, as well as Brave on Android.

Network details:
Tangle  v1.0.0
api v11.0.1
apps v0.136.2-3

**Comment by bee344** [comment]
Same as with #10512 .

**Comment by TarikGul** [comment]
Should be fixed via https://github.com/polkadot-js/apps/pull/10552

**Comment by the-nodelab** [comment]
This is still an issue, even after update to 

api v11.0.3
apps v0.137.2-18

I still have numerous validators and eras displaying possible payouts> When claiming they are all claimed already (tested via extrinsics>staking>payout)

**Comment by TarikGul** [comment]
@the-nodelab What eras are showing as unclaimed that are already claimed?

Is this on Polkadot?

**Comment by TarikGul** [comment]
For polkadot when fixing the API there was one exception for era 1419 where I knew via `claimedRewards` that it was claimed but `erasStakersOverview` would not give any data for that era so I couldn't confirm if it was the right amount of pages claimed. Therefore that Era will still show if it was already claimed. But that was the only one I could see.

**Comment by the-nodelab** [comment]
This is on Tangle:

Tangle Node v1.0.0
api v11.0.3
apps v0.137.2-19

On my view there are currently 25 eras claimable, with only one actually left to be claimed.

If this is working on Polkadot, I presume it must be an issue with the Tangle implementation of it that is the issue. Would that be correct?

**Comment by TarikGul** [comment]
> On my view there are currently 25 eras claimable, with only one actually left to be claimed.

> If this is working on Polkadot, I presume it must be an issue with the Tangle implementation of it that is the issue. Would that be correct?

If you can, can you provide an account for me to query, and I will run it on the API level and share the results with you to see if they look correct.
